name: 'Team Sync'

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'teams.yaml'

jobs:
  synchronize-teams:
    runs-on: ubuntu-latest
    steps:
    - uses: rmacklin/team-sync@v0
      with:
        repo-token: "${{ secrets.ORG_ADMIN_TOKEN }}"
        team-data-path: 'teams.yaml'
